### ISSUE TITLE
手动编辑只能搜索到电影信息，没有电视剧信息

### ISSUE THREAD

**Issue by nortime** [AttemptD/AfuseKt-release#101]
自动刮削成功的电视剧能正常显示，没有刮削出来的电视剧，手动编辑搜索的时候，搜出来的都是电影信息，没有电视剧信息。

**Comment by AttemptD** [comment]
自己找问题发自我的 iPhone在 2024年5月27日，17:09，nortime ***@***.***> 写道：﻿
自动刮削成功的电视剧能正常显示，没有刮削出来的电视剧，手动编辑搜索的时候，搜出来的都是电影信息，没有电视剧信息。
