### ISSUE TITLE
小窗偶现大黑条

### ISSUE THREAD

**Issue by shu458277** [AttemptD/AfuseKt-release#103]
![Screenshot_2024-05-30-13-47-36-988_com android settings](https://github.com/AttemptD/AfuseKt-release/assets/62279383/149fc8dc-764e-4f27-a94f-a96fb3cb8b6c)
复现版本：最近几个版本均存在
使用环境：小米11，安卓14，OS1.0.1.0
                  红米K70，安卓14，OS1.0.15.0，OS1.0.16.0

**Comment by AttemptD** [comment]
暂时无法复现
