### ISSUE TITLE
100%复现的底部导航问题

### ISSUE THREAD

**Issue by KevinQin1991** [AttemptD/AfuseKt-release#106]
你好，非常喜欢你的 App（美观、好用），在使用了一段时间后，发现如下 UI 上的问题：

![AFUSEKT 001](https://github.com/AttemptD/AfuseKt-release/assets/72010222/d1d1ab25-405f-4eb6-9089-2dba98577259)

具体表现为：

1. 正常冷启动打开App，底部导航区到屏幕底部间距正常，参考<1>
2. 此时横置手机，底部导航区到屏幕边缘的间距变大，参考<2>
3. 再次竖置手机，底部导航区到屏幕边缘间距仍然变大，未能回到<1>的状态，参考<3>

本人使用三星 Fold 5（内外屏均复现）、三星 S24 Ultra，均能 100% 复现该问题，希望作者可以在后续版本中修复该问题，让本来就很优雅的 UI 更完美，谢谢。

此外，另有一个无法每次都复现，但出现过几次的问题：
**在点击首页搜索框后，再点击左上角返回按钮，会有几率首页顶部整个搜索框消失。**

**Comment by AttemptD** [comment]
我自己也发现了发自我的 iPhone在 2024年6月5日，11:34，KevinQin1991 ***@***.***> 写道：﻿
你好，非常喜欢你的 App（美观、好用），在使用了一段时间后，发现如下 UI 上的问题：
AFUSEKT.001.png (view on web)
具体表现为：

正常冷启动打开App，底部导航区到屏幕底部间距正常，参考<1>
此时横置手机，底部导航区到屏幕边缘的间距变大，参考<2>
再次竖置手机，底部导航区到屏幕边缘间距仍然变大，未能回到<1>的状态，参考<3>

本人使用三星 Fold 5（内外屏均复现）、三星 S24 Ultra，均能 100% 复现该问题，希望作者可以在后续版本中修复该问题，让本来就很优雅的 UI 更完美，谢谢。
此外，另有一个无法每次都复现，但出现过几次的问题：
在点击首页搜索框后，再点击左上角返回按钮，会有几率首页顶部整个搜索框消失。

**Comment by KevinQin1991** [comment]
好的哈哈，待你更新！期待

**Comment by AttemptD** [comment]
已修复
