### ISSUE TITLE
同一目录有两个视频信息无法选择第二个，选了也会跳第一个。

### ISSUE THREAD

**Issue by 297951014** [AttemptD/AfuseKt-release#108]
RT：因为收集的视频音轨不同有时候需要选择其他
![Uploading Screenshot_2024-06-10-15-15-27-140_com.attempt.af.jpg…]()
视频播放

**Comment by 297951014** [comment]
![Uploading Screenshot_2024-06-10-15-15-27-140_com.attempt.af.jpg…]()

**Comment by 297951014** [comment]
https://pic.imgdb.cn/item/6666a92a5e6d1bfa05faef36.jpg

**Comment by AttemptD** [comment]
没看懂
