### ISSUE TITLE
除了点击左上角的剪头退出，其他方式都不会更新播放进度

### ISSUE THREAD

**Issue by rockhia** [AttemptD/AfuseKt-release#109]
如果不点击左上角的箭头退出。播放进度不会更新。
![Screenshot_20240611_121525_com attempt afusekt_edit_459411258569592](https://github.com/AttemptD/AfuseKt-release/assets/90016652/591603eb-ad52-4877-bc32-27237ab26917)

**Comment by AttemptD** [comment]
最新版已经修复
