### ISSUE TITLE
希望增加调整字幕同步时间功能

### ISSUE THREAD

**Issue by Jenichia** [AttemptD/AfuseKt-release#112]
RT
以期达到字幕显示超前/迟后一段时间的效果，例如图中 MX Player 中的字幕同步调速功能。

![Screenshot_20240614_012307.jpg](https://github.com/AttemptD/AfuseKt-release/assets/87779111/d9e4067d-4644-4928-b319-788198ff3fc2)

**Comment by AttemptD** [comment]
免费用户暂且开放此功能，已经有了
![Screenshot_20240616_084032_AfuseKt.jpg](https://github.com/AttemptD/AfuseKt-release/assets/50815957/82335858-6561-476a-9b59-20d836e337c8)
