### ISSUE TITLE
没有办法，读取嵌套的文件夹这个问题有点严重了，希望可以支持一下！

### ISSUE THREAD

**Issue by huanglian666** [AttemptD/AfuseKt-release#113]
界面做的全是非苹果生态中最精美的了

**Comment by AttemptD** [comment]
暂时没有这个安排发自我的 iPhone在 2024年6月15日，18:21，黄炼 ***@***.***> 写道：﻿
界面做的全是非苹果生态中最精美的了

**Comment by AttemptD** [comment]
一直可以读取嵌套，如果是webdav，请确保自己文件夹中不能有英文标点符号.
