### ISSUE TITLE
在剧集信息界面删除的如何恢复？

### ISSUE THREAD

**Issue by hbtx99099** [AttemptD/AfuseKt-release#114]
![Screenshot_20240615_182426](https://github.com/AttemptD/AfuseKt-release/assets/38598204/5a970d43-a7c7-48e7-aa80-2044b00111b8)
图中右上角删除，刷新库也不会再恢复。是否提供一个恢复删除剧集的界面。
还有个问题，在资源库界面刷新，并不会让网盘中已删除但曾扫入库的剧集消失。

**Comment by AttemptD** [comment]
刷新相关的资源库就行了发自我的 iPhone在 2024年6月15日，18:30，hbtx99099 ***@***.***> 写道：﻿
Screenshot_20240615_182426.jpg (view on web)
图中右上角删除，刷新库也不会再恢复。是否提供一个恢复删除剧集的界面。
还有个问题，在资源库界面刷新，并不会让网盘中已删除但曾扫入库的剧集消失。

**Comment by hbtx99099** [comment]
![Screenshot_20240616_123305](https://github.com/AttemptD/AfuseKt-release/assets/38598204/43f06f91-235e-4444-929b-bf9d279a18e5)
刷新的圈自己转半个小时了，上面的剧集数量没有变化。已删除的去不掉，已有的刷不出来。关应用重开接着转圈。束手无策了。

**Comment by hbtx99099** [comment]
重新连接库，重试了一下。扫完库后去网盘内删除视频，再扫库，被删的视频不会在库中被去除。
