### ISSUE TITLE
列表页问题

### ISSUE THREAD

**Issue by xdaigame** [AttemptD/AfuseKt-release#117]
我记得之前列表页面是三列显示，现在双列显示好大，有点不方便，希望可以增加一个选项，三列，四列显示视图！
![Screenshot_20240617_230444_com attempt afusekt](https://github.com/AttemptD/AfuseKt-release/assets/67528452/408b7a4f-c066-4560-8d90-7ce72f2619bb)

**Comment by AttemptD** [comment]
为了性能和自适应，请自己去手机系统修改你的显示的大小发自我的 iPhone在 2024年6月17日，23:09，﹏老、顽童。 ***@***.***> 写道：﻿
我记得之前列表页面是三列显示，现在双列显示好大，有点不方便，希望可以增加一个选项，三列，四列显示视图！
Screenshot_20240617_230444_com.attempt.afusekt.jpg (view on web)
