### ISSUE TITLE
忘记密码验证码发送显示time out

### ISSUE THREAD

**Issue by yeminxi** [AttemptD/AfuseKt-release#118]
![image](https://github.com/AttemptD/AfuseKt-release/assets/169566216/ebae4557-b82e-4612-ad7c-e1d762447508)

**Comment by AttemptD** [comment]
账号被封了，等明天发自我的 iPhone在 2024年6月18日，12:19，叶泯希 ***@***.***> 写道：﻿
image.png (view on web)

**Comment by AttemptD** [comment]
> > 账号被封了，等明天发自我的 iPhone在 2024年6月18日，12:19，叶泯希 ***@***.***> 写道：﻿ image.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> 
> 好的 谢谢 我想问一下 为啥我的本地smb服务行不通
> ![image](https://github.com/AttemptD/AfuseKt-release/assets/169566216/7a7210e1-56ee-43e3-8223-66e4a633f588)
> 

帐户密码中不能有特殊符号，我猜你密码里面有@或者别的
