### ISSUE TITLE
匹配不到时，希望编辑影视数据的同时修改为视频文件名称

### ISSUE THREAD

**Issue by wu4339** [AttemptD/AfuseKt-release#12]
匹配不到时，希望编辑影视数据的同时修改为视频名称，这样就一劳永逸，以后匹配不用重新再修改

**Comment by shengdaozm** [comment]
是的，当匹配不到的时候(某文件内部只有1.mp4,2.mp4....时)，会自动将每个文件解析成一部电影，整个文件信息都错误，希望能够识别这样的文件夹

**Comment by mr-TY111** [comment]
强烈建议支持“删除自动匹配的元数据”，很多非电影视频匹配到的元数据都是错的，还不能修改

**Comment by AttemptD** [comment]
> 是的，当匹配不到的时候(某文件内部只有1.mp4,2.mp4....时)，会自动将每个文件解析成一部电影，整个文件信息都错误，希望能够识别这样的文件夹

不会去识别文件夹
