### ISSUE TITLE
特定Emby服无法正常播放

### ISSUE THREAD

**Issue by YUNDAN21** [AttemptD/AfuseKt-release#120]
我在使用afusekt观看一个动漫服里面的影片是，出现了加载出来的视频不正确的情况，就是我选择播放的视频与实际不符，且一直是同一个视频，但如果使用另一个播放器播放同一剧集有事可以的，请问这是为什么？具体见下图（图二是使用afusekt播放时出现的异常画面）
![Screenshot_2024-06-19-20-00-58-776_com hush yamby](https://github.com/AttemptD/AfuseKt-release/assets/89337880/0418d12f-03cc-4abe-9793-dd2e4fc58043)

![Screenshot_2024-06-19-20-00-30-309_com attempt afusekt](https://github.com/AttemptD/AfuseKt-release/assets/89337880/84f444ec-7a4b-4f78-8b05-feadbe244710)

**Comment by AttemptD** [comment]
找你腐竹发自我的 iPhone在 2024年6月19日，20:09，YUNDAN21 ***@***.***> 写道：﻿
我在使用afusekt观看一个动漫服里面的影片是，出现了加载出来的视频不正确的情况，就是我选择播放的视频与实际不符，且一直是同一个视频，但如果使用另一个播放器播放同一剧集有事可以的，请问这是为什么？具体见下图
Screenshot_2024-06-19-20-00-58-776_com.hush.yamby.jpg (view on web)
Screenshot_2024-06-19-20-00-30-309_com.attempt.afusekt.jpg (view on web)

**Comment by AttemptD** [comment]
纸片人找腐竹，我无法解决
