### ISSUE TITLE
美少女好

### ISSUE THREAD

**Issue by colatoya** [AttemptD/AfuseKt-release#121]
TV端留下账号：colatoya

感谢

**Comment by AttemptD** [comment]
请勿不要为公开自己账号，想办法私聊我qq还是tg，确保自己能同步资源库发自我的 iPhone在 2024年6月21日，09:11，colatoya ***@***.***> 写道：﻿
TV端留下账号：colatoya
感谢

**Comment by 792532971** [comment]
期待TV版
