### ISSUE TITLE
Afusekt是否支持安卓8.1设备？

### ISSUE THREAD

**Issue by LibraStalker** [AttemptD/AfuseKt-release#126]
我手机是小米5X，安卓版本是8.1，但是安装Afusekt时提示安装包解析错误，是不是不支持安卓8.1设备呀？

**Comment by crrashh1542** [comment]
> 我手机是小米5X，安卓版本是8.1，但是安装Afusekt时提示安装包解析错误，是不是不支持安卓8.1设备呀？

哥们你没看README吗...别人明说了最低安卓11

**Comment by AttemptD** [comment]
目前最低支持9发自我的 iPhone在 2024年7月6日，13:16，LibraStalker ***@***.***> 写道：﻿
Closed #126 as completed.
