### ISSUE TITLE
连接上emby无法使用

### ISSUE THREAD

**Issue by wu4339** [AttemptD/AfuseKt-release#13]
连接上emby无法使用，项目文件夹无法选择，主界面的显示也是空的

**Comment by AttemptD** [comment]
> 连接上emby无法使用，项目文件夹无法选择，主界面的显示也是空的

不使用直连的情况，emby不需要选择，直接右上角的勾即可

**Comment by wu4339** [comment]
> > 连接上emby无法使用，项目文件夹无法选择，主界面的显示也是空的
> 
> 不使用直连的情况，emby不需要选择，直接右上角的勾即可

直连和不直连 主界面emby下都显示空。(上传不了截图总是提示报错)

**Comment by AttemptD** [comment]
> > > 连接上emby无法使用，项目文件夹无法选择，主界面的显示也是空的
> > 
> > 不使用直连的情况，emby不需要选择，直接右上角的勾即可
> 
> 直连和不直连 主界面emby下都显示空。(上传不了截图总是提示报错)![Screenshot_2024-03-10-12-28-53-850_com.example.afusekt-edit.jpg](https://github.com/AttemptD/AfuseKt-release/assets/16701668/e6db422b-e282-4fe1-a1c4-aff72caa2216)
> 
> 
> 

你可以在群里交流730115842
