### ISSUE TITLE
连续播放下字幕显示错误

### ISSUE THREAD

**Issue by Jenichia** [AttemptD/AfuseKt-release#136]
打开软件后播放带字幕的视频，在字幕载完时会显示 ```字幕已下载``` 的 Toast，同时字幕显示是正常的。但是如果这一部播放完自动进入下一部时不会显示 Toast，同时显示的字幕依旧是上一部的，必须要退出重新打开下一部才会正确加载字幕。

我是在 Emby 服务器里播放视频的，说实话这是一个很早就有的 BUG，更新了那么多次我以为早就有人提过这个问题应该修好了，结果刚才一查发现根本没人提，就来这提一下。

**Comment by AttemptD** [comment]
> 打开软件后播放带字幕的视频，在字幕载完时会显示 `字幕已下载` 的 Toast，同时字幕显示是正常的。但是如果这一部播放完自动进入下一部时不会显示 Toast，同时显示的字幕依旧是上一部的，必须要退出重新打开下一部才会正确加载字幕。
> 
> 我是在 Emby 服务器里播放视频的，说实话这是一个很早就有的 BUG，更新了那么多次我以为早就有人提过这个问题应该修好了，结果刚才一查发现根本没人提，就来这提一下。

是用的mpv吗

**Comment by AttemptD** [comment]
> 打开软件后播放带字幕的视频，在字幕载完时会显示 `字幕已下载` 的 Toast，同时字幕显示是正常的。但是如果这一部播放完自动进入下一部时不会显示 Toast，同时显示的字幕依旧是上一部的，必须要退出重新打开下一部才会正确加载字幕。
> 
> 我是在 Emby 服务器里播放视频的，说实话这是一个很早就有的 BUG，更新了那么多次我以为早就有人提过这个问题应该修好了，结果刚才一查发现根本没人提，就来这提一下。

请详细说一下
1.使用什么播放器
2.上一集播放完毕后，进入下一集，下一集的同路径内有没有字幕

**Comment by Jenichia** [comment]
> 请详细说一下
1.使用什么播放器
2.上一集播放完毕后，进入下一集，下一集的同路径内有没有字幕

1. MPV播放器
2. 同路径有字幕，但是字幕文件是上一集的

**Comment by AttemptD** [comment]
已修复，请等待下个版本更新发自我的 iPhone在 2024年7月11日，17:57，Jenichia ***@***.***> 写道：﻿

请详细说一下
1.使用什么播放器
2.上一集播放完毕后，进入下一集，下一集的同路径内有没有字幕


MPV播放器
同路径有字幕，但是字幕文件是上一集的

**Comment by Jenichia** [comment]
1.3.2 版本已修复。
