### ISSUE TITLE
每次打开APP都会有服务器链接失败的提示 

### ISSUE THREAD

**Issue by offid** [AttemptD/AfuseKt-release#143]
升级新版本后每次打开APP都会有服务器链接失败的提示 
![微信图片_20240714095535](https://github.com/user-attachments/assets/e963d05d-bd95-43cb-933a-09a4d96328e8)

**Comment by AttemptD** [comment]
我在与相同出现问题的用户调试，会尽快修复此问题，因为大部分人都没有此问题发自我的 iPhone在 2024年7月14日，09:56，offid ***@***.***> 写道：﻿
升级新版本后每次打开APP都会有服务器链接失败的提示
_20240714095535.jpg (view on web)

**Comment by offid** [comment]
感谢，新版本已经解决了！
