### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by shuaigekda** [AttemptD/AfuseKt-release#159]
手机端挂载alist，刷新资源完毕，当我在alist上面把资源文件更改存放路径之后，手机端重新扫描，不能自动识别路径的更改，直接观看资源会报错，必须先删除，才能在另一个文件夹搜索到

**Comment by AttemptD** [comment]
下个版本将会修复这个问题发自我的 iPhone在 2024年8月8日，08:52，shuaigekda ***@***.***> 写道：﻿
手机端挂载alist，刷新资源完毕，当我在alist上面把资源文件更改存放路径之后，手机端重新扫描，不能自动识别路径的更改，直接观看资源会报错，必须先删除，才能在另一个文件夹搜索到
