### ISSUE TITLE
不支持识别杜比视界，发绿；更换其他APP是正常的

### ISSUE THREAD

**Issue by jiemo9527** [AttemptD/AfuseKt-release#163]

**Comment by AttemptD** [comment]
比如呢发自我的 iPhone在 2024年8月17日，16:45，芥默 ***@***.***> 写道：﻿

**Comment by jiemo9527** [comment]
Jellyfin正常播放，Afusekt发绿

**Comment by AttemptD** [comment]
如果你设备支持杜比，那么exo可以正常播放发自我的 iPhone在 2024年8月17日，20:46，芥默 ***@***.***> 写道：﻿
Jellyfin正常播放，Afusekt发绿
