### ISSUE TITLE
功能建议 好想要

### ISSUE THREAD

**Issue by wazk9595** [AttemptD/AfuseKt-release#164]
可以出个不同线路整合功能吗🥺线路一多起来看起来就好冗杂，好难受

![Screenshot_20240818_055102.jpg](https://github.com/user-attachments/assets/0f4d2d9c-b720-41eb-8909-7f87a108e421)

**Comment by AttemptD** [comment]
有，订阅用户可用，设置开启即可，仅限扫库首页，设置过媒体库首页，不可用发自我的 iPhone在 2024年8月18日，05:53，今をいきる ***@***.***> 写道：﻿
可以出个不同线路整合功能吗🥺线路一多起来看起来就好冗杂，好难受
Screenshot_20240818_055102.jpg (view on web)

**Comment by wazk9595** [comment]
> 有，订阅用户可用，设置开启即可，仅限扫库首页，设置过媒体库首页，不可用发自我的 iPhone在 2024年8月18日，05:53，今をいきる ***@***.***> 写道：﻿
> 可以出个不同线路整合功能吗🥺线路一多起来看起来就好冗杂，好难受
> Screenshot_20240818_055102.jpg (view on web)
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

设置里没看到有啊

**Comment by wazk9595** [comment]
不是聚合搜索啊 是像yybx那样可以一个名称下多条线路，美观便利

**Comment by AttemptD** [comment]
有一个版本有，不过去掉了，对公益媒体服务，压力太大发自我的 iPhone在 2024年8月18日，13:44，今をいきる ***@***.***> 写道：﻿
不是聚合搜索啊 是像yybx那样可以一个名称下多条线路，美观便利

**Comment by wazk9595** [comment]
可以加个开关不
