### ISSUE TITLE
添加本地存储无效

### ISSUE THREAD

**Issue by lvrayman** [AttemptD/AfuseKt-release#168]
选中文件夹后授予权限，资源库里面有对应的文件夹，但没有出来任何媒体，文件夹和文件名命名都是规范的，也尝试把nfo文件放了进去，都没有用。
这个问题用了很多个版本都是存在的，手机是小米

**Comment by AttemptD** [comment]
是的，目前本地存储是有问题的发自我的 iPhone在 2024年8月21日，09:22，lvrayman ***@***.***> 写道：﻿
选中文件夹后授予权限，资源库里面有对应的文件夹，但没有出来任何媒体，文件夹和文件名命名都是规范的，也尝试把nfo文件放了进去，都没有用。
这个问题用了很多个版本都是存在的，手机是小米

**Comment by lvrayman** [comment]
@AttemptD 有无修复计划，整体体验挺好的，能完善本地存储就完美了

**Comment by AttemptD** [comment]
等我的设备到了吧，自己的设备系统有bug无法使用本地发自我的 iPhone在 2024年8月21日，15:14，lvrayman ***@***.***> 写道：﻿
@AttemptD 有无修复计划，整体体验挺好的，能完善本地存储就完美了
