### ISSUE TITLE
登录可以改改

### ISSUE THREAD

**Issue by PoiYuudachi** [AttemptD/AfuseKt-release#17]
既然有个https的开关，那地址可以不需要以http开头，默认就可以了

**Comment by youthlin** [comment]
lets encript 的ssl是不认吗，总是提示连接失败

**Comment by AttemptD** [comment]
> lets encript 的ssl是不认吗，总是提示连接失败

不清楚

**Comment by AttemptD** [comment]
> 既然有个https的开关，那地址可以不需要以http开头，默认就可以了

好的

**Comment by PoiYuudachi** [comment]
> > 既然有个https的开关，那地址可以不需要以http开头，默认就可以了
> 
> 好的

emby这种媒体服务器的，本身就已经刮削好了，就没必要扫库了，默认直连就好

**Comment by youthlin** [comment]
> lets encript 的ssl是不认吗，总是提示连接失败

破案了，搜了下是因为ssl没有配置中间证书。改为用fullchain证书（它含中间证书）和私钥就好了（群晖）
