### ISSUE TITLE
emby海报问题

### ISSUE THREAD

**Issue by Jz1028** [AttemptD/AfuseKt-release#170]
现在是emby的海报是正常的
afusekt挂载emby的海报有错误，点进去之后也是有的正确有的错误
emby
![image](https://github.com/user-attachments/assets/6509c036-fd05-4e29-a183-68fa2d5958fb)
![image](https://github.com/user-attachments/assets/3e9589c9-09fb-4f4a-ba40-9de8f17587e1)
afusekt
![image](https://github.com/user-attachments/assets/375f28b2-cbf3-4602-a273-766328badb83)
![image](https://github.com/user-attachments/assets/95ba25fa-ccb1-4a7b-a7af-cd931e9100af)

**Comment by AttemptD** [comment]
尝试去app通用设置，清除缓存试试发自我的 iPhone在 2024年8月26日，17:23，Jz ***@***.***> 写道：﻿
现在是emby的海报是正常的
afusekt挂载emby的海报有错误，点进去之后也是有的正确有的错误
emby
image.png (view on web)
image.png (view on web)
afusekt
image.png (view on web)
image.png (view on web)

**Comment by Jz1028** [comment]
清除缓存，都没有反应。
只有去emby删除元数据，这边才是空。但是只要重新刷新，这边又错了
