### ISSUE TITLE
可以登录 获取内容但是播放会报错当前视频链接无法播放

### ISSUE THREAD

**Issue by Kitterato** [AttemptD/AfuseKt-release#174]

**Comment by AttemptD** [comment]
什么协议发自我的 iPhone在 2024年9月5日，09:21，Kitterato ***@***.***> 写道：﻿

**Comment by Kitterato** [comment]
https

**Comment by AttemptD** [comment]
媒体服务的话，无法播放请尝试打开服务不转码发自我的 iPhone在 2024年9月7日，10:05，Kitterato ***@***.***> 写道：﻿
https

**Comment by Kitterato** [comment]
使用emy_unlock docket镜像本地搭建 走内外网都会报错这个

**Comment by Kitterato** [comment]
> 媒体服务的话，无法播放请尝试打开服务不转码发自我的 iPhone在 2024年9月7日，10:05，Kitterato ***@***.***> 写道：﻿ https —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: 

> 媒体服务的话，无法播放请尝试打开服务不转码发自我的 iPhone在 2024年9月7日，10:05，Kitterato ***@***.***> 写道：﻿ https —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

好的 开启后已解决

**Comment by Kitterato** [comment]
顺便问一下 是否不支持emby家庭视频与照片类型的媒体库 这种媒体库点进去只能查看列表缩略图 无法播放

**Comment by AttemptD** [comment]
是的仅支持电影与电视剧类型目前发自我的 iPhone在 2024年9月7日，10:22，Kitterato ***@***.***> 写道：﻿
顺便问一下 是否不支持emby家庭视频与照片类型的媒体库 这种媒体库点进去只能查看列表缩略图 无法播放

**Comment by Kitterato** [comment]
> 是的仅支持电影与电视剧类型目前发自我的 iPhone在 2024年9月7日，10:22，Kitterato ***@***.***> 写道：﻿ 顺便问一下 是否不支持emby家庭视频与照片类型的媒体库 这种媒体库点进去只能查看列表缩略图 无法播放 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

好的 感谢解答
