### ISSUE TITLE
播放视频报错

### ISSUE THREAD

**Issue by sunrise1998** [AttemptD/AfuseKt-release#175]
我是使用alist挂载115，可以读取内容，但播放报错；更换webdav更是无法连接，大神能帮忙解读一下不？
![Uploading Screenshot_20240907_135553.jpg…]()

**Comment by AttemptD** [comment]
加tg讨论群吧，去群里问问发自我的 iPhone在 2024年9月7日，13:56，sunrise1998 ***@***.***> 写道：﻿
我是使用alist挂载115，可以读取内容，但播放报错；更换webdav更是无法连接，大神能帮忙解读一下不？
