### ISSUE TITLE
希望支持123云盘的WebDAV

### ISSUE THREAD

**Issue by konjoker** [AttemptD/AfuseKt-release#177]
123云盘现在支持WebDAV协议，我试了一下afusekt可以访问到123云盘内的文件但是不能读取到文件夹内的视频，就算读取到了却提示没法播放，filmly这个软件就可以读取并播放123云盘WebDAV的文件

**Comment by AttemptD** [comment]
地址栏您应该填错了地址栏只填域名，最后的/webdav要填在路径输入框发自我的 iPhone在 2024年9月16日，02:19，konjoker ***@***.***> 写道：﻿
123云盘现在支持WebDAV协议，我试了一下afusekt可以访问到123云盘内的文件但是不能读取到文件夹内的视频，就算读取到了却提示没法播放，filmly这个软件就可以读取并播放123云盘WebDAV的文件

**Comment by konjoker** [comment]
问题解决了，谢谢您
