### ISSUE TITLE
用tmm搜刮的字幕无法显示

### ISSUE THREAD

**Issue by zhufeizzz** [AttemptD/AfuseKt-release#178]
![image](https://github.com/user-attachments/assets/80ca4ffc-8541-474e-85a3-6db44edabf8b)

![b85c6e8b57233cf1c6a2d95c98d9a34](https://github.com/user-attachments/assets/0f23a7cb-ae15-405b-9b3a-477b8a894165)

![2366e399e6cbfda0e165757a9db5088](https://github.com/user-attachments/assets/78e19a61-05e2-47e6-bc66-9ff10825e188)

**Comment by AttemptD** [comment]
vlc的播放器bug，已修复
