### ISSUE TITLE
能不能做成程序内在线升级

### ISSUE THREAD

**Issue by jackyronin** [AttemptD/AfuseKt-release#18]
每次都需要删除程序重新安装更新版本，原来添加的都要重新来一次。有新版本自动在线更新就好了啊

**Comment by AttemptD** [comment]
> 每次都需要删除程序重新安装更新版本，原来添加的都要重新来一次。有新版本自动在线更新就好了啊

作者的服务器撑不住，所以只能以这样的方式，但你可以直接覆盖安装，不需要卸载重装

**Comment by shaguaphm** [comment]
作者其实可以弹窗让更新，然后给个按钮让跳转到gitee发行版的页面，让用户不用魔法上网下载最新版的，这样直接跳转，也不用负担服务器的
