### ISSUE TITLE
阿里云盘里的国产电视剧识别错

### ISSUE THREAD

**Issue by leiguoqian** [AttemptD/AfuseKt-release#180]
我存在阿里云盘里的国产电视剧，名称和海报全错了，美剧没问题，用filmly试了一下可以正常识别

**Comment by AttemptD** [comment]
刮削问题看关于里面的手册发自我的 iPhone在 2024年9月27日，17:15，leiguoqian ***@***.***> 写道：﻿
我存在阿里云盘里的国产电视剧，名称和海报全错了，美剧没问题，用filmly试了一下可以正常识别
