### ISSUE TITLE
三星fold6 查看所有标签下的bug

### ISSUE THREAD

**Issue by zjwangliwei** [AttemptD/AfuseKt-release#183]
进入查看所有的标签下横向旋转或者竖向旋转都会出现封面左右间距不等比和竖向间距不等比的情况.
![Uploading Screenshot_20241009_201558_AfuseKt.jpg…]()
![Screenshot_20241009_201439_AfuseKt.jpg](https://github.com/user-attachments/assets/8fb3cdc4-dc59-4c6f-a09a-95fa6b924250)

![Screenshot_20241009_201558_AfuseKt.jpg](https://github.com/user-attachments/assets/ae423164-1017-4d78-ac47-660593ee6d46)

**Comment by zjwangliwei** [comment]
打开手机自动旋转,进入查看所有,然后旋转手机方向,海报间距不正确,手机竖向状态进入查看所有和横向状态进入查看所有,然后再旋转方向都会出现这个情况

**Comment by AttemptD** [comment]
下个版本修复
