### ISSUE TITLE
alist显示当前播放链接无法播放，用其他nova family等可以正常播放

### ISSUE THREAD

**Issue by wq475065319** [AttemptD/AfuseKt-release#187]

**Comment by wq475065319** [comment]
当前播放链接无法播放
https://cdnfhnfile.115.com/5f520f67cb8d9144518a5b5d217b26d 7ddc8edda/Mulan.2020.1080p.WEBRip.DDP5.1.×264-EVO%5BEt HD%5D.mkv?t=1729874176&u=9529430&5=524288000&d=vip -1875243614-awbhbpp9uetyth43g-1&c=2&f=1&k=b221c77563aad4e879362b4881d98233&us=5242880000&uc=10&v=1

**Comment by AttemptD** [comment]
115走webdav
