### ISSUE TITLE
什么时候能够支持杜比视界

### ISSUE THREAD

**Issue by jackyronin** [AttemptD/AfuseKt-release#19]
软件已经做得很不错了，刮削非常快，测试过目前还不支持杜比视界，有点小遗憾，再就是等待TV版了，安卓TV版才是这个软件该存在的地方。

**Comment by AttemptD** [comment]
> 软件已经做得很不错了，刮削非常快，测试过目前还不支持杜比视界，有点小遗憾，再就是等待TV版了，安卓TV版才是这个软件该存在的地方。

害，不会写
