### ISSUE TITLE
tv版本，登录报错 403

### ISSUE THREAD

**Issue by szh811218** [AttemptD/AfuseKt-release#193]
AfusektV-arm-release_1.4.0-10190-02-chinese.apk
版本是上述版本
安装在小米电视上

**Comment by AttemptD** [comment]
tv不提供免费，请自行去购买界面使用测试账号测试发自我的 iPhone在 2024年11月10日，21:03，szh811218 ***@***.***> 写道：﻿
AfusektV-arm-release_1.4.0-10190-02-chinese.apk
版本是上述版本
安装在小米电视上

**Comment by szh811218** [comment]
请教一下，如何购买

**Comment by szh811218** [comment]
没有安卓手机，有安卓平板，可以购买tv版本吗？

**Comment by AttemptD** [comment]
可以，先进tg，与大家交流交流发自我的 iPhone在 2024年11月11日，08:04，szh811218 ***@***.***> 写道：﻿
没有安卓手机，有安卓平板，可以购买tv版本吗？
