### ISSUE TITLE
关于emby分类隐藏事宜

### ISSUE THREAD

**Issue by Myth1-1** [AttemptD/AfuseKt-release#194]
诸如hill、yamby、femor分类都可以隐藏，做成本地就行，不会影响，可以参考femor的这个细节
![Screenshot_2024-11-16-21-01-25-900-edit_com.mountains.hills.jpg](https://github.com/user-attachments/assets/6e6882f3-f962-4261-9c45-62c0b5e97d6c)

**Comment by AttemptD** [comment]
你也可隐藏，设置，通用，媒体服务发自我的 iPhone在 2024年11月16日，21:04，Myth ***@***.***> 写道：﻿
诸如hill、yamby、femor分类都可以隐藏，做成本地就行，不会影响，可以参考femor的这个细节
Screenshot_2024-11-16-21-01-25-900-edit_com.mountains.hills.jpg (view on web)

**Comment by Myth1-1** [comment]
欧克，我试试

**Comment by Myth1-1** [comment]
是这样可以具体开关的这种，做成本地就行
![Screenshot_2024-11-16-22-09-40-415-edit_com.mountains.hills.jpg](https://github.com/user-attachments/assets/2a6cba2a-5138-426f-b5a0-6d33dc194a6f)

**Comment by Myth1-1** [comment]
是这样可以具体分类开关的，并不是显示几行就行，femor做成本地的可以参考下
![Screenshot_2024-11-16-22-09-40-415-edit_com.mountains.hills.jpg](https://github.com/user-attachments/assets/ae774208-9b02-4898-b330-a16e571e1ff5)
