### ISSUE TITLE
Jellyfin播放不了

### ISSUE THREAD

**Issue by codepotato-reset** [AttemptD/AfuseKt-release#196]
APP1.41版本，jellyfin 10.10版本，媒体库类型是家庭视频和照片，视频能看到预览图，但是点击没有反应。目前只能通过播放记录点开视频观看

**Comment by AttemptD** [comment]
媒体服务暂仅支持剧集与电影，其他类型没写发自我的 iPhone在 2024年11月17日，21:21，codepotato-reset ***@***.***> 写道：﻿
APP1.41版本，jellyfin 10.10版本，媒体库类型是家庭视频和照片，视频能看到预览图，但是点击没有反应。目前只能通过播放记录点开视频观看

**Comment by codepotato-reset** [comment]
> 媒体服务暂仅支持剧集与电影，其他类型没写发自我的 iPhone在 2024年11月17日，21：21，codepotato-reset ***@***.***> 写道： APP1.41版本，jellyfin 10.10版本，媒体库类型是家庭视频和照片，视频能看到预览图，但是点击没有反应。目前只能通过播放记录点开视频观看 —直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

收到，感谢回复，希望后续能更新这部分功能
