### ISSUE TITLE
关于emby的显示问题

### ISSUE THREAD

**Issue by jackyronin** [AttemptD/AfuseKt-release#20]
添加多个EMBY服务器的时候，无法对不同的服务器进行区分，在首页只会重复按照添加顺序显示，备注也无法体现标题中。建议对EMBY服务器名称做标识。如果能把EMBY直连的界面采取分页显示将更好，以区别alist或webdav等资源库。最后，期待能对接阿里云盘和夸克云盘。

**Comment by AttemptD** [comment]
> 添加多个EMBY服务器的时候，无法对不同的服务器进行区分，在首页只会重复按照添加顺序显示，备注也无法体现标题中。建议对EMBY服务器名称做标识。如果能把EMBY直连的界面采取分页显示将更好，以区别alist或webdav等资源库。最后，期待能对接阿里云盘和夸克云盘。

这点会优化，时间问题，阿里网盘在开发中
