### ISSUE TITLE
Add option to choose video player

### ISSUE THREAD

**Issue by qooode** [AttemptD/AfuseKt-release#24]
I would like to have the option to choose the video player. It would be easier to find subtitles and also there are features already implemented in existing video players such as VLC, MX Player etc.

**Comment by AttemptD** [comment]
> I would like to have the option to choose the video player. It would be easier to find subtitles and also there are features already implemented in existing video players such as VLC, MX Player etc.

now i try to use mpv，when i fail ，i will do that
