### ISSUE TITLE
是否会有“启用外部播放器”的功能？

### ISSUE THREAD

**Issue by Ma-Huan2001** [AttemptD/AfuseKt-release#26]
大佬你好，目前软件好像无法播放杜比视界视频，可否添加启用外部播放器的功能？这样就可以用mx player之类的播放器来播放几乎所有格式的视频，这样感觉你也会比较轻松，不用去适配各种视频格式了。谢谢

**Comment by AttemptD** [comment]
> 大佬你好，目前软件好像无法播放杜比视界视频，可否添加启用外部播放器的功能？这样就可以用mx player之类的播放器来播放几乎所有格式的视频，这样感觉你也会比较轻松，不用去适配各种视频格式了。谢谢
可能会，但不确定
