### ISSUE TITLE
视频列表

### ISSUE THREAD

**Issue by llxs720** [AttemptD/AfuseKt-release#27]
感谢大佬做的软件，安卓端太需要了！全部视频列表视频目前展示2行，希望缩小一些，改成3行或者4行

**Comment by AttemptD** [comment]
> 感谢大佬做的软件，安卓端太需要了！全部视频列表视频目前展示2行，希望缩小一些，改成3行或者4行

这是根据你手机来得，你可以试试横屏就知道了
