### ISSUE TITLE
A little advice

### ISSUE THREAD

**Issue by Glyco-Protein** [AttemptD/AfuseKt-release#29]
You can write a brief description in the project description so that it can be retrieved.

![image](https://github.com/AttemptD/AfuseKt-release/assets/156641373/b830b109-02b9-46d6-9289-3b63352961e1)

**Comment by AttemptD** [comment]
> You can write a brief description in the project description so that it can be retrieved.
> 
> ![image](https://github.com/AttemptD/AfuseKt-release/assets/156641373/b830b109-02b9-46d6-9289-3b63352961e1)
> 
thank for your advice
