### ISSUE TITLE
提示不是最新版

### ISSUE THREAD

**Issue by Labrador-QAQ** [AttemptD/AfuseKt-release#31]
![Screenshot_20240319-171757_AfuseKt.png](https://github.com/AttemptD/AfuseKt-release/assets/61800879/e09b8e9b-cfa5-4a1a-ba03-47dd738fa9c2)

**Comment by AttemptD** [comment]
> ![Screenshot_20240319-171757_AfuseKt.png](https://github.com/AttemptD/AfuseKt-release/assets/61800879/e09b8e9b-cfa5-4a1a-ba03-47dd738fa9c2)
> 
> 

之前没放出来
