### ISSUE TITLE
怎么使用第三方播放器呀？

### ISSUE THREAD

**Issue by Yzcloud** [AttemptD/AfuseKt-release#32]
你好，请问如何使用第三方播放器呢？勾选了使用第三方播放器然后播放的时候没有选项呀，长按也没反应？

**Comment by AttemptD** [comment]
> 你好，请问如何使用第三方播放器呢？勾选了使用第三方播放器然后播放的时候没有选项呀，长按也没反应？

没写开关只是个开关，假的

**Comment by Yzcloud** [comment]
> > 你好，请问如何使用第三方播放器呢？勾选了使用第三方播放器然后播放的时候没有选项呀，长按也没反应？
> 
> 没写开关只是个开关，假的

好吧😂
