### ISSUE TITLE
华为手机，系统为鸿蒙4.0版本无法安装软件

### ISSUE THREAD

**Issue by kofzhanganguo** [AttemptD/AfuseKt-release#35]
我下载了AfuseKt-1.3.9，AfuseKt-1.4.0，都无法在华为手机鸿蒙4.0系统中安装，其他APK的安卓软件都可以正常安装。

**Comment by AttemptD** [comment]
> 我下载了AfuseKt-1.3.9，AfuseKt-1.4.0，都无法在华为手机鸿蒙4.0系统中安装，其他APK的安卓软件都可以正常安装。

安卓11及以上

**Comment by chaomarks** [comment]
> 我下载了AfuseKt-1.3.9，AfuseKt-1.4.0，都无法在华为手机鸿蒙4.0系统中安装，其他APK的安卓软件都可以正常安装。

安卓10和鸿蒙3.0也装不了，好难过
