### ISSUE TITLE
alist 添加时 无法选中文件夹，一直提示请选择一个来源

### ISSUE THREAD

**Issue by gcczmx** [AttemptD/AfuseKt-release#36]
![Screenshot_20240320_202733_com example afusekt](https://github.com/AttemptD/AfuseKt-release/assets/30593830/ec5adfd2-bea5-4c9c-b197-41f5b846acdc)

**Comment by AttemptD** [comment]
> ![Screenshot_20240320_202733_com example afusekt](https://github.com/AttemptD/AfuseKt-release/assets/30593830/ec5adfd2-bea5-4c9c-b197-41f5b846acdc)
> 

点击文件夹选中，边缘进入目录

**Comment by mr-TY111** [comment]
点方块儿中间的文件夹图标。。。。
我刚开始也没发现

**Comment by gcczmx** [comment]
> 点方块儿中间的文件夹图标。。。。 我刚开始也没发现

还真是，😅
