### ISSUE TITLE
Translate To English 

### ISSUE THREAD

**Issue by notabhixhek** [AttemptD/AfuseKt-release#4]
Please Add English Translation

**Comment by crrashh1542** [comment]
> I already have this plan ,please wait for language trans

感觉可以开个Crowdin项目，让社区参与进翻译工作中

**Comment by AttemptD** [comment]
已经适配大部分了发自我的 iPhone在 2024年4月25日，13:01，Kotsuki Crrashh ***@***.***> 写道：﻿

I already have this plan ,please wait for language trans

感觉可以开个Crowdin项目，让社区参与进翻译工作中

**Comment by AttemptD** [comment]
﻿已经适配大部分了发自我的 iPhone在 2024年4月25日，13:01，Kotsuki Crrashh ***@***.***> 写道：﻿

I already have this plan ,please wait for language trans

感觉可以开个Crowdin项目，让社区参与进翻译工作中
