### ISSUE TITLE
有一些电视剧还是没有元数据呢，重新编辑搜索也没有

### ISSUE THREAD

**Issue by AfanChang** [AttemptD/AfuseKt-release#40]
rt
![Screenshot_2024-03-26-18-37-50-405_com example afusekt](https://github.com/AttemptD/AfuseKt-release/assets/45871658/d6b9f2b2-0174-4c5c-a358-89fe73552535)
![Screenshot_2024-03-26-18-37-27-490_com example afusekt](https://github.com/AttemptD/AfuseKt-release/assets/45871658/95e76903-11cd-40f6-bf0e-d7adfeed9a99)

**Comment by AttemptD** [comment]
> rt
> ![Screenshot_2024-03-26-18-37-50-405_com example afusekt](https://github.com/AttemptD/AfuseKt-release/assets/45871658/d6b9f2b2-0174-4c5c-a358-89fe73552535)
> ![Screenshot_2024-03-26-18-37-27-490_com example afusekt](https://github.com/AttemptD/AfuseKt-release/assets/45871658/95e76903-11cd-40f6-bf0e-d7adfeed9a99)
> 

名字不规范被识别成电影了，电影无法搜索电视剧

**Comment by AfanChang** [comment]
请问有电视剧和电影的命名规则吗，谢谢啦

**Comment by AttemptD** [comment]
规则s01e01以此类推发自我的 iPhone在 2024年3月26日，20:53，AfanChang ***@***.***> 写道：﻿
请问有电视剧和电影的命名规则吗，谢谢啦
