### ISSUE TITLE
能不能发个覆盖安装的版本？

### ISSUE THREAD

**Issue by mzlipro** [AttemptD/AfuseKt-release#48]
忘记之前是哪个邮箱注册的了…新版本可以看到注册邮箱号，可不可以给一个可以覆盖安装，让我看看旧版本上的是哪个邮箱。

**Comment by mzlipro** [comment]
还有目前小窗的比例有点怪，其他软件的小窗是正常的，这个小窗有点过长，似乎是根据手机屏幕比例缩小，而不是根据视频比例缩小。
![Uploading S40331-12094696_com.attempt.afusekt.png…]()
![Uploading S40401-20430081_com.example.hikerview.png…]()

**Comment by mzlipro** [comment]
![S40331-12094696_com attempt afusekt](https://github.com/AttemptD/AfuseKt-release/assets/80456523/941203a2-ccf7-4cda-9381-d5a99c15cdc5)

**Comment by mzlipro** [comment]
![Uploading S40401-20430081_com.example.hikerview.png…]()

**Comment by mzlipro** [comment]
![S40401-20430081_com example hikerview](https://github.com/AttemptD/AfuseKt-release/assets/80456523/52934bca-de65-4cd7-8b82-0b16665a529a)

**Comment by AttemptD** [comment]
下个版本修复发自我的 iPhone在 2024年4月1日，20:45，mzlipro ***@***.***> 写道：﻿
还有目前小窗的比例有点怪，其他软件的小窗是正常的，这个小窗有点过长，似乎是根据手机屏幕比例缩小，而不是根据视频比例缩小。

**Comment by AttemptD** [comment]
不可了，谷歌上架必须修改发自我的 iPhone在 2024年3月31日，11:46，mzlipro ***@***.***> 写道：﻿
忘记之前是哪个邮箱注册的了…新版本可以看到注册邮箱号，可不可以给一个可以覆盖安装，让我看看旧版本上的是哪个邮箱。

**Comment by mzlipro** [comment]
> 不可了，谷歌上架必须修改发自我的 iPhone在 2024年3月31日，11:46，mzlipro ***@***.***> 写道：﻿ 忘记之前是哪个邮箱注册的了…新版本可以看到注册邮箱号，可不可以给一个可以覆盖安装，让我看看旧版本上的是哪个邮箱。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

不能单独私发邮箱给我一个吗？
