### ISSUE TITLE
建议加入一个路径浏览视图

### ISSUE THREAD

**Issue by meetyoucrash** [AttemptD/AfuseKt-release#50]
建议加入一个路径浏览视图，可以浏览所有刮削成功以及没有刮削成功的文件，没有刮削成功过的可以直接显示文件名称，有个统一的未刮削成功封面不影响美观即可。现在的情况是一个文件没有刮削到信息就没法浏览观看

**Comment by AttemptD** [comment]
> 建议加入一个路径浏览视图，可以浏览所有刮削成功以及没有刮削成功的文件，没有刮削成功过的可以直接显示文件名称，有个统一的未刮削成功封面不影响美观即可。现在的情况是一个文件没有刮削到信息就没法浏览观看

阿里云不提供，无解
