### ISSUE TITLE
资源库emby需要呈列表显示

### ISSUE THREAD

**Issue by Myth1-1** [AttemptD/AfuseKt-release#52]
资源库emby呈现列表显示,能一眼看清楚

**Comment by AttemptD** [comment]
为多库设计的发自我的 iPhone在 2024年4月2日，10:25，Myth ***@***.***> 写道：﻿
资源库emby呈现列表显示,能一眼看清楚

**Comment by ZACKLZ** [comment]
可以将所有来源归集整理，媒体资料上可以标注来源（阿里云盘/emby等）

**Comment by AttemptD** [comment]
一看就是知道是你发自我的 iPhone在 2024年4月2日，15:11，小刘忙 ***@***.***> 写道：﻿
可以将所有来源归集整理，媒体资料上可以标注来源（阿里云盘/emby等）

**Comment by ZACKLZ** [comment]
> 一看就是知道是你发自我的 iPhone在 2024年4月2日，15:11，小刘忙 ***@***.***> 写道：﻿ 可以将所有来源归集整理，媒体资料上可以标注来源（阿里云盘/emby等） —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

大佬认识我？= =
