### ISSUE TITLE
建议，将剧集放播放页面的选集改成不带图的

### ISSUE THREAD

**Issue by chaomarks** [AttemptD/AfuseKt-release#59]
只有文字那种，第几季第几集

**Comment by AttemptD** [comment]
可切换，自己切换就行了发自我的 iPhone在 2024年4月7日，00:42，chaomarks ***@***.***> 写道：﻿
只有文字那种，第几季第几集

**Comment by chaomarks** [comment]
> 可切换，自己切换就行了发自我的 iPhone在 2024年4月7日，00:42，chaomarks ***@***.***> 写道：﻿ 只有文字那种，第几季第几集 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

大佬，正在播放的页面没有啊，播放前选集数的页面倒是可以切换
