### ISSUE TITLE
添加jellyfin之后资源库中的电影电视剧等信息未更新

### ISSUE THREAD

**Issue by Jia-Shen** [AttemptD/AfuseKt-release#61]
添加jellyfin之后资源库中的电影电视剧等信息未更新，版本1.1.2fix

**Comment by AttemptD** [comment]
直连不入库，载首页底部发自我的 iPhone在 2024年4月8日，15:45，Chuck Shen ***@***.***> 写道：﻿
添加jellyfin之后资源库中的电影电视剧等信息未更新，版本1.1.2fix
