### ISSUE TITLE
请问元数据刮削查询是哪个接口? TMDB or OMDB

### ISSUE THREAD

**Issue by rokre2** [AttemptD/AfuseKt-release#64]
很多影片都无法进行刮削，排除手工匹规则。总结存在以下问题：

1.  部分电视剧，无法手工刮削（排除网络问题，因为不使用科学上网，完全不能显示图片），查询不到数据。比如：乾隆王朝，Qian Long Wang Chao，Qian Long Dynasty 均无法查询到影片元数据。实际在IMDB,豆瓣,TMDB, TMDB-api（由自己测试），均可以查询得到。 
2. 令人费解的事，第二天在未调整文件名，更新app的情况，居然又可以自动获取 “乾隆王朝” 的元数据，太过神奇。

根据以上结论，请问作者告知使用哪个平台做的元数据查询: 

- IMDB（可能性不大）
- TMDB
- OMDB 
- 豆瓣（可能性不大）

**Comment by AttemptD** [comment]
电视剧命名需要正确s01e01，不然会被识别成电影，导致无法搜索到发自我的 iPhone在 2024年4月9日，18:31，rokre2 ***@***.***> 写道：﻿
很多影片都无法进行刮削，排除手工匹规则。总结存在以下问题：

部分电视剧，无法手工刮削（排除网络问题，因为大部分电影都是可以刮削的），查询不到数据。比如：乾隆王朝，Qian Long Wang Chao，Qian Long Dynasty 均无法查询到影片元数据。实际在IMDB,豆瓣,TMDB, TMDB-api（由自己测试），均可以查询得到。
令人费解的事，第二天在未调整文件名，更新app的情况，居然又可以自动获取 “乾隆王朝” 的元数据，太过神奇。

根据以上结论，请问作者告知使用哪个平台做的元数据查询:

IMDB（可能性不大）
TMDB
OMDB
豆瓣（可能性不大）

**Comment by Haowen0706** [comment]
大佬，刮削数据不全。例如最近的新剧，命名 春色寄情人.E01   ，在TMDB内能搜到，iPad端vidhub端也能匹配，但是在手机软件内搜不到，即使手动输入春色寄情人，也无法搜到相关剧名进行匹配

**Comment by AttemptD** [comment]
你这个命名不对，你这个代表第几季呢发自我的 iPhone在 2024年4月28日，00:49，Haowen0706 ***@***.***> 写道：﻿
大佬，刮削数据不全。例如最近的新剧，命名 春色寄情人.E01   ，在TMDB内能搜到，iPad端vidhub端也能匹配，但是在手机软件内搜不到，即使手动输入春色寄情人，也无法搜到相关剧名进行匹配

**Comment by buildyuan** [comment]
> 大佬，刮削数据不全。例如最近的新剧，命名 春色寄情人.E01 ，在TMDB内能搜到，iPad端vidhub端也能匹配，但是在手机软件内搜不到，即使手动输入春色寄情人，也无法搜到相关剧名进行匹配

 春色寄情人.S01E01

**Comment by AttemptD** [comment]
请问你你这个是第几季，我单看，我看不出来，第10季还是第0季，你不名字中写出来，app怎么知道你这个是电视剧发自我的 iPhone在 2024年5月8日，14:54，Yuan ***@***.***> 写道：﻿

大佬，刮削数据不全。例如最近的新剧，命名 春色寄情人.E01 ，在TMDB内能搜到，iPad端vidhub端也能匹配，但是在手机软件内搜不到，即使手动输入春色寄情人，也无法搜到相关剧名进行匹配

春色寄情人.S01E01
