### ISSUE TITLE
jellyfin下面strm格式的文件无法播放

### ISSUE THREAD

**Issue by pengs361** [AttemptD/AfuseKt-release#66]
可以扫出来视频文件，但是无法播放strm格式文件

**Comment by pengs361** [comment]
1.1.3

**Comment by AttemptD** [comment]
> 1.1.3

https://github.com/AttemptD/AfuseKt-release/assets/50815957/4ce47709-6b6b-4a9e-9543-571870a8c505

**Comment by ghxtgh** [comment]
1.3.2 strm中如果是http链接依旧不能播放，一直加载转圈
