### ISSUE TITLE
增加读取本地开关

### ISSUE THREAD

**Issue by gaodyoffice** [AttemptD/AfuseKt-release#70]
好多电影都刮削过的，但是用afusekt存在刮削错了，可能需要重新命名。
建议增加读取开关，用于读取已刮削的电影。例如，但实际我是用tmm刮削好的。
![Screenshot_2024-04-22-22-38-05-515_com.attempt.afusekt.jpg](https://github.com/AttemptD/AfuseKt-release/assets/100499224/5220ef2d-c5a0-488b-b1b0-e1d26f9ab159)

**Comment by AttemptD** [comment]
不会增加增加此功能，至少目前不会发自我的 iPhone在 2024年4月22日，22:40，gaodyoffice ***@***.***> 写道：﻿
好多电影都刮削过的，但是用afusekt存在刮削错了，可能需要重新命名。
建议增加读取开关，用于读取已刮削的电影。例如，但实际我是用tmm刮削好的。
Screenshot_2024-04-22-22-38-05-515_com.attempt.afusekt.jpg (view on web)
