### ISSUE TITLE
可以设置不搜刮元数据吗

### ISSUE THREAD

**Issue by ijava-debug** [AttemptD/AfuseKt-release#73]
保存的视频看完就删的，懒得去重命名了，不命名的话自动搜刮的元数据是乱的，搞得不知道哪个文件是我刚保存的，设置里面好像不能设置关闭元数据搜刮？

**Comment by AttemptD** [comment]
> 保存的视频看完就删的，懒得去重命名了，不命名的话自动搜刮的元数据是乱的，搞得不知道哪个文件是我刚保存的，设置里面好像不能设置关闭元数据搜刮？

不可
