### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by Eercanlly** [AttemptD/AfuseKt-release#79]
识别不到文件同名字幕，必须内嵌的才行，希望支持ass和srt等常规字幕

**Comment by AttemptD** [comment]
一直都可，在右上角同路径字幕发自我的 iPhone在 2024年5月8日，19:23，Eercanlly ***@***.***> 写道：﻿
识别不到文件同名字幕，必须内嵌的才行，希望支持ass和srt等常规字幕
