### ISSUE TITLE
其他的视频希望可以支持视频缩略图

### ISSUE THREAD

**Issue by wu4339** [AttemptD/AfuseKt-release#8]
其他的视频希望可以支持视频缩略图

**Comment by AttemptD** [comment]
这个无法获取，尝试过了

**Comment by wu4339** [comment]
> 这个无法获取，尝试过了

Nova video play 是可以有缩略图的，但是不好用。

**Comment by ypq123456789** [comment]
> 这个无法获取，尝试过了

可以类似nplayer那样从视频里面抽帧生成缩略图吗
