### ISSUE TITLE
删除单集

### ISSUE THREAD

**Issue by shu458277** [AttemptD/AfuseKt-release#83]
希望能够增加删除单集，或者多选几集删除，现在默认好像是只能删除某个电视剧的某一整个季，而且只是不在软件内显示，并不会删除源文件，希望能够优化

**Comment by AttemptD** [comment]
自然不可能去删除源文件，这不是文件管理器发自我的 iPhone在 2024年5月10日，15:42，shu458277 ***@***.***> 写道：﻿
希望能够增加删除单集，或者多选几集删除，现在默认好像是只能删除某个电视剧的某一整个季，而且只是不在软件内显示，并不会删除源文件，希望能够优化
