### ISSUE TITLE
刮削失败的文件，修改文件名重新刮削后，失败记录不清除

### ISSUE THREAD

**Issue by RedTearsss** [AttemptD/AfuseKt-release#84]
刮削失败后的文件标记为其他，网盘中重新重命名重新刮削后，刮削成功，之前失败的其他记录也仍在不清除。

**Comment by AttemptD** [comment]
需要你手动同步，同步比较慢发自我的 iPhone在 2024年5月10日，15:42，RedTearsss ***@***.***> 写道：﻿
刮削失败后的文件标记为其他，网盘中重新重命名重新刮削后，刮削成功，之前失败的其他记录也仍在不清除。

**Comment by RedTearsss** [comment]
> 需要你手动同步，同步比较慢发自我的 iPhone在 2024年5月10日，15:42，RedTearsss ***@***.***> 写道：﻿ 刮削失败后的文件标记为其他，网盘中重新重命名重新刮削后，刮削成功，之前失败的其他记录也仍在不清除。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

修改文件之后主动进行了一次手动同步，确实比较慢，看起来是全量扫描了一遍，但是并没有清除之前的刮削失败的记录，挨个手动删除的。

**Comment by AttemptD** [comment]
1.2.7-10054已经修复
