### ISSUE TITLE
希望增加批量重命名和删除功能,这样在软件里就可以操作完成,不用来回切换网盘

### ISSUE THREAD

**Issue by Invincible-World** [AttemptD/AfuseKt-release#91]
希望增加批量重命名和删除功能,这样在软件里就可以操作完成,不用来回切换网盘

**Comment by AttemptD** [comment]
软件本质还是要去你网盘获取数据，为了避免误操作，在本软件删除后导致网盘数据丢失，所以，还是需要你去修改网盘内容，最新版已经修复更爱文件后，af本地刷新不删除旧数据问题
