### ISSUE TITLE
希望能支持服务端转码

### ISSUE THREAD

**Issue by fuliaojiyue** [AttemptD/AfuseKt-release#93]
我使用jellyfin的，这个软件播放很合适我使用习惯，就是在外面使用不能转码手机流量顶不住，希望能添加一个调用服务端转码的功能，谢谢

**Comment by AttemptD** [comment]
你支付服务器费用吗？发自我的 iPhone在 2024年5月18日，18:57，fuliaojiyue ***@***.***> 写道：﻿
我使用jellyfin的，这个软件播放很合适我使用习惯，就是在外面使用不能转码手机流量顶不住，希望能添加一个调用服务端转码的功能，谢谢
