### ISSUE TITLE
大佬反馈个 bug

### ISSUE THREAD

**Issue by Kai-le1212** [AttemptD/AfuseKt-release#98]
老哥反馈个 bug（版本 1.2.5），
vivo X70t（处理器 猎户座 1080） 点击登录/注册按钮会闪退，无法登录，
看看能不能解决一下
十分感谢🙏
（在酷安说的也是我☺️）

**Comment by AttemptD** [comment]
更新最新的发自我的 iPhone在 2024年5月25日，16:39，Kai-le1212 ***@***.***> 写道：﻿
老哥反馈个 bug（版本 1.2.5），
vivo X70t（处理器 猎户座 1080） 点击登录/注册按钮会闪退，无法登录，
看看能不能解决一下
十分感谢🙏
（在酷安说的也是我☺️）

**Comment by Yahiuu** [comment]
服务器关闭注册，你直接更新就行了，退出账号或删除程序就无法在登录，等服务器打开才可以用，应该就这几天时间，可以去tg了解最新动态
