### ISSUE TITLE
自定义字幕选项

### ISSUE THREAD

**Issue by zxjmovie** [AttemptD/AfuseKt-release#99]
非常感谢您提供如此周到的播放器工具，能否在未来的更新中加入srt字幕的自定义选项，比如可以调整字幕的位置、字号、字体、轮廓阴影、同步延迟等功能…目前字幕置底，不能调整同步和大小。

**Comment by AttemptD** [comment]
该功能仅提供给未来的付费用户，目前仅拥有测试权限的人才可使用该功能发自我的 iPhone在 2024年5月26日，09:18，zxjmovie ***@***.***> 写道：﻿
非常感谢您提供如此周到的播放器工具，能否在未来的更新中加入srt字幕的自定义选项，比如可以调整字幕的位置、字号、字体、轮廓阴影、同步延迟等功能…目前字幕置底，不能调整同步和大小。
